In [1]:
import torch

# Senaryo: Bir katmandaki aktivasyonlara (4 nöron) bias eklemek
# Batch size = 3, Nöron sayısı = 4
activations = torch.ones(3, 4) 
biases = torch.tensor([[10, 20, 30, 40]]) # Shape: (1, 4)

# Rule 1 devreye girer: (1, 4) -> (3, 4) gibi davranır
result = activations + biases

print(f"Activations shape: {activations.shape}")
print(f"Biases shape: {biases.shape}")
print(f"Result shape: {result.shape}")
print("\nSonuç Matrisi:\n", result)

Activations shape: torch.Size([3, 4])
Biases shape: torch.Size([1, 4])
Result shape: torch.Size([3, 4])

Sonuç Matrisi:
 tensor([[11., 21., 31., 41.],
        [11., 21., 31., 41.],
        [11., 21., 31., 41.]])


In [4]:
# import torch

x = torch.tensor([1, 2, 3, 4]) # Shape: (4,)
print(f"Orijinal Shape: {x.shape}")

# Başına 1 boyutlu boş bir boyut ekleyelim
x_expanded = x[None, :] # Shape: (1, 4)
# Veya
x_expanded_alt = x.unsqueeze(0) # Shape: (1, 4)

print(f"Genişletilmiş Shape: {x_expanded.shape}")

# Şimdi (5, 4) bir matrisle hatasız toplanabilir
matrix = torch.ones(5, 4)
result = matrix + x_expanded # Broadcasting otomatik çalışır
result

Orijinal Shape: torch.Size([4])
Genişletilmiş Shape: torch.Size([1, 4])


tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])

In [5]:
# import torch

A = torch.randn(10, 5, 5)
B = torch.randn(5)

# Otomatik (Implicit) Rule 2 + Rule 1
result_auto = A + B 

# Manuel (Explicit) Rule 2: 'unsqueeze' veya 'None' kullanımı
# Bu yöntem Rule 2'nin yaptığı işi elle yapar
B_explicit = B.unsqueeze(0).unsqueeze(0) # Shape: (1, 1, 5)
# Veya daha şık bir yol:
B_explicit_alt = B[None, None, :] # Shape: (1, 1, 5)

print(f"B original: {B.shape}")
print(f"B explicit: {B_explicit.shape}")

B original: torch.Size([5])
B explicit: torch.Size([1, 1, 5])


In [6]:

out = torch.zeros((2, 3, 1)) + torch.zeros((7, 2, 1, 5))
out.shape

torch.Size([7, 2, 3, 5])

In [7]:
import torch

# Örnek: (2, 3) matrisine her satır için bir çarpan eklemek istiyoruz
A = torch.ones(2, 3)
B = torch.tensor([10, 20]) # Shape: (2,)

# HATA: A + B -> Rule 3 nedeniyle B'yi (1, 2) yapmaya çalışır. 
# (2, 3) ile (1, 2) hizalanamaz (3 != 2).

# ÇÖZÜM: Manuel olarak sağa boyut ekle (Rule 2'yi elle uygula)
B_new = B.unsqueeze(1) # Shape: (2, 1)
result = A + B_new # Artık (2, 3) ile (2, 1) uyumlu!
result

tensor([[11., 11., 11.],
        [21., 21., 21.]])